# ------------------------------------------------------------------- ( server init )
server.port=${TASKS_PORT}
spring.application.name=tasks
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
management.endpoints.web.exposure.include=health, refresh
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
# -------------------------------------------------------------------- ( server end )

# --------------------------------------------------------------------- ( logs init )
logging.level.root=ERROR
logging.file.name = ./src/main/resources/logs/logfile.log
logging.pattern.file=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}, %-5level, %file [%method], %thread, %msg%n
# ---------------------------------------------------------------------- ( logs end )

# ----------------------------------------------------------------- ( env test init )
spring.config.import=optional:file:.env[.properties]
# ----------------------------------------------------------------- ( env test end )

# --------------------------------------------------------------- ( H2 DB test init )
spring.datasource.url=jdbc:h2:mem:tasksdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.flyway.enabled=true
spring.flyway.create-schemas=false
spring.flyway.schemas=PUBLIC
spring.flyway.default-schema=PUBLIC
spring.flyway.table=flyway_schema_history
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ---------------------------------------------------------------- ( H2 DB test end )