# ------------------------------------------------------------------- ( server init )
server.port=${TASKS_PORT}
spring.application.name=tasks
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
management.endpoints.web.exposure.include=health, refresh
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
# -------------------------------------------------------------------- ( server end )

# --------------------------------------------------------------------- ( logs init )
logging.level.root=ERROR
logging.file.name = ./src/main/resources/logs/logfile.log
logging.pattern.file=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}, %-5level, %file [%method], %thread, %msg%n
# ---------------------------------------------------------------------- ( logs end )

# ----------------------------------------------------------------- ( database init )
# JPA
spring.datasource.url=jdbc:${TASKS_DATABASE_TYPE}://database:${DATABASE_PORT}/${TASKS_DATABASE_NAME}
spring.datasource.username=${TASKS_DATABASE_USER}
spring.datasource.password=${TASKS_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=${TASKS_DATABASE_SCHEMA}

# Flyway
spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.schemas=${TASKS_DATABASE_SCHEMA}
spring.flyway.default-schema=${TASKS_DATABASE_SCHEMA}
spring.flyway.table=${TASKS_FLYWAY_TABLE}
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=true
# ------------------------------------------------------------------ ( database end )

# ---------------------------------------------------------------- ( messaging init )
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=messaging:${MESSAGING_PORT}

# SASL security configuration
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
  username="${TASKS_MESSAGING_USER}" \
  password="${TASKS_MESSAGING_PASSWORD}";

# Consumer configuration
spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate

# Deserialization (generic, raw bytes)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.properties.enable.idempotence=false
spring.kafka.producer.acks=all
spring.kafka.producer.retries=0
spring.kafka.producer.properties.request.timeout.ms=15000
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.producer.properties.max.block.ms=15000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.batch.size=0
# ----------------------------------------------------------------- ( messaging end )