# -------------------------------------------------------------- ( server init )
spring.application.name=helloworld
server.port=${HELLOWORLD_PORT}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
management.endpoints.web.exposure.include=health, refresh
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
# --------------------------------------------------------------- ( server end )

# ---------------------------------------------------------------- ( logs init )
logging.level.root=ERROR
logging.structured.format.console=logstash
# ----------------------------------------------------------------- ( logs end )