apiVersion: apps/v1
kind: Deployment

metadata:
    name: tasks

spec:
    replicas: 1
    selector:
        matchLabels:
            app: tasks
    template:
        metadata:
            labels:
                app: tasks
        spec:
            containers:
                - name: tasks
                  image: docker.io/library/tasks:latest
                  imagePullPolicy: Never
                  ports:
                      - name: service-port
                        containerPort: 3011
                  envFrom:
                      - configMapRef:
                          name: app-config
                  livenessProbe:
                      httpGet:
                          path: /actuator/health/liveness
                          port: service-port
                      initialDelaySeconds: 10
                      periodSeconds: 30
                      timeoutSeconds: 10
                      failureThreshold: 5