apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: production
type: Opaque
stringData:
    # Common
    APPLICATION_TITLE: "dolistico"
    PUBLIC_DOMAIN: "request.juliokozarewicz.com"
    DOCUMENTATION_BASE_URL: "api/v1/documentation"
    HELLOWORLD_BASE_URL: "api/v1/helloworld"
    HELLOWORLD_PORT: "3002"

    # Nginx
    NGINX_PORT: "80"