apiVersion: apps/v1
kind: Deployment

metadata:
  name: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_ADMIN_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_ADMIN_PASSWORD
        - name: DATABASE_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_ADMIN_USER
        - name: DATABASE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_ADMIN_PASSWORD
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - pg_isready -U "$DATABASE_ADMIN_USER" -d postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-pvc