# ------------------------------------------------------ (init documentation)

# ===========================================================================
# [ DOCUMENTATION - Stoplight Elements ]
# ===========================================================================

location = /api/v1/documentation {
    return 301 /api/v1/documentation/;
}

location /api/v1/documentation/ {
    alias /static/public/documentation/elements/;
    index index.html;
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "public";
    limit_req zone=general_zone burst=50 nodelay;
}

# ===========================================================================
# [ DOCUMENTATION - Swagger ]
# ===========================================================================

location = /api/v1/documentation/swagger {
    return 301 /api/v1/documentation/swagger/;
}

location /api/v1/documentation/swagger {
    alias /static/public/documentation/swagger/;
    index index.html;
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "public";
    limit_req zone=general_zone burst=50 nodelay;
}

# ------------------------------------------------------- (end documentation)