# -------------------------------------------------------- (init hello world)

# [ HELLO WORLD - Static Files ]
location /api/v1/helloworld/static {
    proxy_pass http://helloworld_backend;
    limit_req zone=general_zone burst=5 nodelay;
}

# [ HELLO WORLD - Helloworld ]
location /api/v1/helloworld {
    proxy_pass http://helloworld_backend;
    limit_req zone=general_zone burst=5 nodelay;
}

# --------------------------------------------------------- (end hello world)