# ---------------------------------------------------------------------- (init tasks)

# [ TASKS ]
location /api/v1/tasks {
    proxy_pass http://tasks_backend;
    limit_req zone=general_zone burst=5 nodelay;
}

# ----------------------------------------------------------------------- (end tasks)