# -------------------------------------------------------------- ( server init )
spring.application.name=emailservice
server.port=${EMAIL_SERVICE_PORT}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
management.endpoints.web.exposure.include=health, refresh
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
# --------------------------------------------------------------- ( server end )

# ---------------------------------------------------------------- ( logs init )
logging.level.root=ERROR
logging.structured.format.console=logstash
# ----------------------------------------------------------------- ( logs end )

# --------------------------------------------------- ( email credentials init )
spring.mail.host=${EMAIL_SERVICE_HOST}
spring.mail.port=${EMAIL_SERVICE_PORT}
spring.mail.username=${EMAIL_SERVICE_ADDRESS_USER}
spring.mail.password=${EMAIL_SERVICE_PASSWORD}
spring.mail.properties.mail.smtp.auth=${EMAIL_SERVICE_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_SERVICE_START_TTLS}
# ---------------------------------------------------- ( email credentials end )

# ----------------------------------------------------------- ( messaging init )
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=messaging:${MESSAGING_PORT}

# SASL security configuration
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
  username="${EMAIL_SERVICE_MESSAGING_USER}" \
  password="${EMAIL_SERVICE_MESSAGING_PASSWORD}";

# Consumer configuration
spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate

# Deserialization (generic, raw bytes)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.properties.enable.idempotence=false
spring.kafka.producer.acks=all
spring.kafka.producer.retries=0
spring.kafka.producer.properties.request.timeout.ms=15000
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.producer.properties.max.block.ms=15000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.batch.size=0
# ------------------------------------------------------------ ( messaging end )