apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

secretGenerator:

  # ------------------------------------------------------ ( load secrets init )
  # Cloudflare
  - name: cloudflared-secrets
    envs:
      - secrets/cloudflared.env

    # Database
  - name: database-secrets
    envs:
      - secrets/database.env

  # Cache
  - name: cache-secrets
    envs:
      - secrets/cache.env

  # Messaging
  - name: messaging-secrets
    envs:
      - secrets/messaging.env

  # Tasks
  - name: tasks-secrets
    envs:
      - secrets/tasks.env

  # ------------------------------------------------------- ( load secrets end )

generatorOptions:
  disableNameSuffixHash: true