apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secrets
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: /APP_NAME/cloudflared/TUNNEL_TOKEN