# ------------------------------------------ (rate limiting and bots config init)

map $http_x_forwarded_for $real_client_ip {
    default $remote_addr;
    "~^(?P<first_ip>[^,]+)" $first_ip;
}

limit_req_zone $real_client_ip zone=critical_zone:100m rate=5r/m;
limit_req_zone $real_client_ip zone=general_zone:150m rate=20r/m;
limit_req_zone $real_client_ip zone=almost_free_zone:200m rate=100r/m;
limit_conn_zone $real_client_ip zone=conn_limit_zone:100m;
limit_conn conn_limit_zone 10;
limit_req_status 429;

# Blocking due to suspicious User-Agent (bots, scanners, etc.)
map $http_user_agent $bad_ua {
    default 0;
    "~*(curl|wget|python-requests|masscan|nmap|nikto|sqlmap|bot|scraper)" 1;
    "~*Docker-Healthcheck" 0;
}

# Special log for DDOS attacks or limits reached
log_format ddos '$remote_addr - $http_host "$request" $status [$time_local] '
                '"$http_user_agent" "$http_referer" '
                'req_time=$request_time upstream_time=$upstream_response_time';
access_log /var/log/nginx/ddos.log ddos;

# ------------------------------------------- (rate limiting and bots config end)