# ----------------------------------------------------- (upstream load balancer init)

upstream helloworld_backend {
    zone helloworld_backend 64k;
    server helloworld:3002 resolve;
}

upstream accounts_backend {
    zone accounts_backend 64k;
    server accounts:3003 resolve;
}

upstream tasks_backend {
    zone tasks_backend 64k;
    server tasks:3004 resolve;
}

# ------------------------------------------------------ (upstream load balancer end)