# ----------------------------------------------------- (upstream load balancer init)

upstream helloworld_backend {
    zone helloworld_backend 64k;
    server helloworld.production.svc.cluster.local:3001 resolve;
}

upstream accounts_backend {
    zone accounts_backend 64k;
    server accounts.production.svc.cluster.local:3002 resolve;
}

upstream tasks_backend {
    zone tasks_backend 64k;
    server tasks.production.svc.cluster.local:3003 resolve;
}

# ------------------------------------------------------ (upstream load balancer end)