apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:

    # ------------------------------------------------------------ (config init)

    # Namespace
    - namespace.yaml

    # 1_config
    - 1_config/app-config.yaml
    - 1_config/cloudflared-secrets.yaml

    # ------------------------------------------------------------ (config end)

    # ---------------------------------------------------- (infrastructure init)

    # Cloudflare
    - 2_infrastructure/cloudflared/deployment.yaml

    # Nginx
    - 2_infrastructure/nginx/deployment.yaml
    - 2_infrastructure/nginx/service.yaml

    # Database
    - 2_infrastructure/database/deployment.yaml
    - 2_infrastructure/database/pvc.yaml
    - 2_infrastructure/database/service.yaml

    # ----------------------------------------------------- (infrastructure end)

    # ---------------------------------------------------------- (services init)

    # Helloworld
    - 3_services/helloworld/deployment.yaml
    - 3_services/helloworld/service.yaml

    # ----------------------------------------------------------- (services end)