apiVersion: apps/v1
kind: Deployment

metadata:
  name: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: DATABASE_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_ADMIN_USER
        - name: DATABASE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_ADMIN_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sh
          subPath: init.sh
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "$(DATABASE_ADMIN_USER)", "-d", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: database-pvc
      - name: init-script
        hostPath:
          path: /home/fedora/Documents/dolistico/k8s/1_config/database/init.sh
          type: File