#!/bin/bash
set -e

# --------------------------------------
# ACCOUNTS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOF

-- Create schema
CREATE SCHEMA IF NOT EXISTS "${ACCOUNTS_DATABASE_SCHEMA}";

-- Create user
CREATE USER "${ACCOUNTS_DATABASE_USER}" WITH PASSWORD '${ACCOUNTS_DATABASE_PASSWORD}';

-- Grant access only to this schema
GRANT USAGE, CREATE ON SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";

-- Allow user to access future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${ACCOUNTS_DATABASE_USER}";
EOF

# --------------------------------------
# TASKS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOF

CREATE SCHEMA IF NOT EXISTS "${TASKS_DATABASE_SCHEMA}";

CREATE USER "${TASKS_DATABASE_USER}" WITH PASSWORD '${TASKS_DATABASE_PASSWORD}';

GRANT USAGE, CREATE ON SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${TASKS_DATABASE_USER}";

EOF
