#!/bin/bash
set -e

# ================================================================= ( accounts init )

# 1) USER e DATABASE
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname postgres <<-EOF

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles
        WHERE rolname = '${ACCOUNTS_DATABASE_USER}'
    ) THEN
        CREATE USER "${ACCOUNTS_DATABASE_USER}"
        WITH PASSWORD '${ACCOUNTS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

CREATE DATABASE "${ACCOUNTS_DATABASE_NAME}"
OWNER "${ACCOUNTS_DATABASE_USER}";

REVOKE ALL ON DATABASE "${ACCOUNTS_DATABASE_NAME}" FROM PUBLIC;
GRANT CONNECT ON DATABASE "${ACCOUNTS_DATABASE_NAME}" TO "${ACCOUNTS_DATABASE_USER}";

EOF

# 2) Schema and permissions
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${ACCOUNTS_DATABASE_NAME}" <<-EOF

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS "${ACCOUNTS_DATABASE_SCHEMA}";

ALTER SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
OWNER TO "${ACCOUNTS_DATABASE_USER}";

GRANT ALL PRIVILEGES ON SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
TO "${ACCOUNTS_DATABASE_USER}";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
TO "${ACCOUNTS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
TO "${ACCOUNTS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
TO "${ACCOUNTS_DATABASE_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON TABLES TO "${ACCOUNTS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON SEQUENCES TO "${ACCOUNTS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON FUNCTIONS TO "${ACCOUNTS_DATABASE_USER}";

ALTER ROLE "${ACCOUNTS_DATABASE_USER}"
SET search_path = "${ACCOUNTS_DATABASE_SCHEMA}";

EOF
# ================================================================== ( accounts end )

# ==================================================================== ( tasks init )

# 1) USER and DATABASE
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname postgres <<-EOF

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles
        WHERE rolname = '${TASKS_DATABASE_USER}'
    ) THEN
        CREATE USER "${TASKS_DATABASE_USER}"
        WITH PASSWORD '${TASKS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

CREATE DATABASE "${TASKS_DATABASE_NAME}"
OWNER "${TASKS_DATABASE_USER}";

REVOKE ALL ON DATABASE "${TASKS_DATABASE_NAME}" FROM PUBLIC;
GRANT CONNECT ON DATABASE "${TASKS_DATABASE_NAME}" TO "${TASKS_DATABASE_USER}";

EOF

# 2) Schema and permissions
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${TASKS_DATABASE_NAME}" <<-EOF

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS "${TASKS_DATABASE_SCHEMA}";

ALTER SCHEMA "${TASKS_DATABASE_SCHEMA}"
OWNER TO "${TASKS_DATABASE_USER}";

GRANT ALL PRIVILEGES ON SCHEMA "${TASKS_DATABASE_SCHEMA}"
TO "${TASKS_DATABASE_USER}";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
TO "${TASKS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
TO "${TASKS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
TO "${TASKS_DATABASE_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON TABLES TO "${TASKS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON SEQUENCES TO "${TASKS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
GRANT ALL PRIVILEGES ON FUNCTIONS TO "${TASKS_DATABASE_USER}";

ALTER ROLE "${TASKS_DATABASE_USER}"
SET search_path = "${TASKS_DATABASE_SCHEMA}";

EOF
# ===================================================================== ( tasks end )