apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:

    # ------------------------------------------------------------ (config init)

    # Namespace
    - namespace.yaml

    # 1_config
    - 1_config/app-config.yaml

    # ------------------------------------------------------------ (config end)

    # ---------------------------------------------------- (infrastructure init)

    # Cloudflare
    - 2_infrastructure/cloudflared/deployment.yaml

    # Nginx
    - 2_infrastructure/nginx/deployment.yaml
    - 2_infrastructure/nginx/service.yaml

    # Database
    - 2_infrastructure/database/database-init.yaml
    - 2_infrastructure/database/deployment.yaml
    - 2_infrastructure/database/pvc.yaml
    - 2_infrastructure/database/service.yaml

    # Cache
    - 2_infrastructure/cache/cache-init.yaml
    - 2_infrastructure/cache/deployment.yaml
    - 2_infrastructure/cache/pvc.yaml
    - 2_infrastructure/cache/service.yaml

    # Messaging
    - 2_infrastructure/messaging/messaging-init.yaml
    - 2_infrastructure/messaging/deployment.yaml
    - 2_infrastructure/messaging/pvc.yaml
    - 2_infrastructure/messaging/service.yaml

    # ----------------------------------------------------- (infrastructure end)

    # ---------------------------------------------------------- (services init)

    # Helloworld
    - 3_services/helloworld/deployment.yaml
    - 3_services/helloworld/service.yaml

    # ----------------------------------------------------------- (services end)

# ---------------------------------------------------------------- ( jobs init )
configMapGenerator:
  - name: database-init-script
    files:
      - 2_infrastructure/database/init.sh

  - name: cache-init-script
    files:
      - 2_infrastructure/cache/init.sh

  - name: messaging-init-script
    files:
      - 2_infrastructure/messaging/init.sh
# ----------------------------------------------------------------- ( jobs end )

generatorOptions:
  disableNameSuffixHash: true